from datetime import datetime, timedelta

from sqlalchemy.orm import Session

from app.models import (
    Department,
    Feedback,
    Issue,
    IssueSupport,
    IssueUpdate,
    Poll,
    PollOption,
    PollVote,
)
from app.services import category_to_department, compute_priority_score


DEPARTMENT_SEED = [
    ("Roads Department", "RD", "Maintenance of roads and street infrastructure.", 4.6, 4.4),
    ("Solid Waste Management", "SWM", "Garbage collection, segregation and waste operations.", 3.9, 4.6),
    ("Water Department", "WD", "Water supply, pipelines and drainage services.", 4.2, 4.5),
    ("Electrical Department", "ED", "Street light and power infrastructure management.", 5.1, 4.3),
    ("Traffic Management", "TM", "Traffic flow and road safety management.", 4.8, 4.2),
    ("Public Transport", "PT", "Bus and transit services optimization.", 5.3, 4.1),
    ("Public Safety", "PS", "Emergency response and community safety services.", 3.5, 4.4),
    ("Parks Department", "PD", "Urban parks, greenery and recreation amenities.", 6.0, 4.6),
    ("City Administration", "CA", "Cross-city governance and coordination.", 6.2, 4.0),
]

ISSUE_SEED = [
    {
        "ticket_id": "URB-2026-00001",
        "title": "Major pothole near station road",
        "description": "Large pothole has formed near the station road causing damage to bikes and difficulty for pedestrians.",
        "category": "Road & Potholes",
        "area": "Mira Road",
        "landmark": "Near Station Road",
        "latitude": 19.2854,
        "longitude": 72.8697,
        "priority": "High",
        "status": "In Progress",
        "citizen_name": "Aisha Mehta",
        "email": "aisha@example.com",
        "phone": "9867543412",
        "support_count": 18,
        "created_at": datetime.utcnow() - timedelta(days=3),
        "updated_at": datetime.utcnow() - timedelta(days=1),
        "department": "Roads Department",
    },
    {
        "ticket_id": "URB-2026-00002",
        "title": "Street light outage on park lane",
        "description": "Multiple street lights are not working on Park Lane creating unsafe conditions after dark.",
        "category": "Street Lights",
        "area": "Bhayandar",
        "landmark": "Park Lane",
        "latitude": 19.3030,
        "longitude": 72.8504,
        "priority": "Medium",
        "status": "Assigned",
        "citizen_name": "Rohit Patel",
        "email": "rohit@example.com",
        "phone": "9988776655",
        "support_count": 11,
        "created_at": datetime.utcnow() - timedelta(days=5),
        "updated_at": datetime.utcnow() - timedelta(days=2),
        "department": "Electrical Department",
    },
    {
        "ticket_id": "URB-2026-00003",
        "title": "Water leakage near residential block",
        "description": "A leaking pipe is causing water pooling near the residential complex and affecting access.",
        "category": "Water Supply",
        "area": "Kandivali",
        "landmark": "Residential Block 4",
        "latitude": 19.2068,
        "longitude": 72.8535,
        "priority": "Critical",
        "status": "Verified",
        "citizen_name": "Priya Shah",
        "email": "priya@example.com",
        "phone": "9876543210",
        "support_count": 23,
        "created_at": datetime.utcnow() - timedelta(days=1),
        "updated_at": datetime.utcnow() - timedelta(days=1),
        "department": "Water Department",
    },
    {
        "ticket_id": "URB-2026-00004",
        "title": "Garbage overflow near market square",
        "description": "Trash bins are overflowing near the market square and attracting stray animals.",
        "category": "Garbage & Waste",
        "area": "Borivali",
        "landmark": "Market Square",
        "latitude": 19.2301,
        "longitude": 72.8597,
        "priority": "High",
        "status": "Reported",
        "citizen_name": "Nikhil Joshi",
        "email": "nikhil@example.com",
        "phone": "9765432109",
        "support_count": 16,
        "created_at": datetime.utcnow() - timedelta(days=2),
        "updated_at": datetime.utcnow() - timedelta(days=1),
        "department": "Solid Waste Management",
    },
    {
        "ticket_id": "URB-2026-00005",
        "title": "Open drain causing flooding",
        "description": "Drainage covers are broken and water remains stagnant after the recent rain.",
        "category": "Drainage",
        "area": "Dahisar",
        "landmark": "Main Road Flyover",
        "latitude": 19.2660,
        "longitude": 72.8631,
        "priority": "High",
        "status": "Assigned",
        "citizen_name": "Sonia Nair",
        "email": "sonia@example.com",
        "phone": "9823014567",
        "support_count": 20,
        "created_at": datetime.utcnow() - timedelta(days=4),
        "updated_at": datetime.utcnow() - timedelta(days=3),
        "department": "Water Department",
    },
    {
        "ticket_id": "URB-2026-00006",
        "title": "Traffic signal not working",
        "description": "The traffic signal at the junction is malfunctioning and causing congestion.",
        "category": "Traffic",
        "area": "Malad",
        "landmark": "Junction Square",
        "latitude": 19.1886,
        "longitude": 72.8426,
        "priority": "Critical",
        "status": "In Progress",
        "citizen_name": "Rakesh Verma",
        "email": "rakesh@example.com",
        "phone": "9823456789",
        "support_count": 29,
        "created_at": datetime.utcnow() - timedelta(days=1),
        "updated_at": datetime.utcnow() - timedelta(hours=6),
        "department": "Traffic Management",
    },
    {
        "ticket_id": "URB-2026-00007",
        "title": "Bus stop shelter damaged",
        "description": "The shelter roof is broken and commuters are exposed to rain and heat.",
        "category": "Public Transport",
        "area": "Mira Road",
        "landmark": "Bus Depot Road",
        "latitude": 19.2858,
        "longitude": 72.8728,
        "priority": "Medium",
        "status": "Resolved",
        "citizen_name": "Neha Kulkarni",
        "email": "neha@example.com",
        "phone": "9876123456",
        "support_count": 8,
        "created_at": datetime.utcnow() - timedelta(days=9),
        "updated_at": datetime.utcnow() - timedelta(days=2),
        "resolved_at": datetime.utcnow() - timedelta(days=2),
        "department": "Public Transport",
    },
    {
        "ticket_id": "URB-2026-00008",
        "title": "Poor lighting in public park",
        "description": "The walkway and jogging track are dimly lit after sunset affecting safety.",
        "category": "Parks",
        "area": "Bhayandar",
        "landmark": "City Park Entry",
        "latitude": 19.2942,
        "longitude": 72.8481,
        "priority": "Medium",
        "status": "Verified",
        "citizen_name": "Harshad Shah",
        "email": "harshad@example.com",
        "phone": "9898012345",
        "support_count": 13,
        "created_at": datetime.utcnow() - timedelta(days=6),
        "updated_at": datetime.utcnow() - timedelta(days=4),
        "department": "Parks Department",
    },
    {
        "ticket_id": "URB-2026-00009",
        "title": "Loud DJ noise near residential lane",
        "description": "Nighttime noise from a social gathering is causing disturbance to nearby residents.",
        "category": "Noise Pollution",
        "area": "Borivali",
        "landmark": "Residential Lane 3",
        "latitude": 19.2167,
        "longitude": 72.8450,
        "priority": "Low",
        "status": "Reported",
        "citizen_name": "Madhuri Rao",
        "email": "madhuri@example.com",
        "phone": "9761234567",
        "support_count": 6,
        "created_at": datetime.utcnow() - timedelta(days=5),
        "updated_at": datetime.utcnow() - timedelta(days=3),
        "department": "Public Safety",
    },
    {
        "ticket_id": "URB-2026-00010",
        "title": "Broken railings on footpath",
        "description": "Damaged footpath railings pose a hazard to elderly citizens.",
        "category": "Road & Potholes",
        "area": "Kandivali",
        "landmark": "Opposite Temple Complex",
        "latitude": 19.2099,
        "longitude": 72.8588,
        "priority": "Medium",
        "status": "In Progress",
        "citizen_name": "Anil Kumar",
        "email": "anil@example.com",
        "phone": "9811223344",
        "support_count": 14,
        "created_at": datetime.utcnow() - timedelta(days=7),
        "updated_at": datetime.utcnow() - timedelta(days=1),
        "department": "Roads Department",
    },
    {
        "ticket_id": "URB-2026-00011",
        "title": "Public safety concern at bus stop",
        "description": "There is inadequate lighting and a security concern at the late-night bus stop.",
        "category": "Public Safety",
        "area": "Dahisar",
        "landmark": "Bus Stop 8",
        "latitude": 19.2707,
        "longitude": 72.8663,
        "priority": "High",
        "status": "Assigned",
        "citizen_name": "Varun Iyer",
        "email": "varun@example.com",
        "phone": "9922334455",
        "support_count": 19,
        "created_at": datetime.utcnow() - timedelta(days=2),
        "updated_at": datetime.utcnow() - timedelta(days=1),
        "department": "Public Safety",
    },
    {
        "ticket_id": "URB-2026-00012",
        "title": "Water tank overflow at colony",
        "description": "Overflow from a water tank is creating a standing water issue near the colony gate.",
        "category": "Water Supply",
        "area": "Mira Road",
        "landmark": "Colony Gate",
        "latitude": 19.2821,
        "longitude": 72.8708,
        "priority": "Medium",
        "status": "Resolved",
        "citizen_name": "Sheetal Desai",
        "email": "sheetal@example.com",
        "phone": "9666112233",
        "support_count": 9,
        "created_at": datetime.utcnow() - timedelta(days=11),
        "updated_at": datetime.utcnow() - timedelta(days=6),
        "resolved_at": datetime.utcnow() - timedelta(days=6),
        "department": "Water Department",
    },
    {
        "ticket_id": "URB-2026-00013",
        "title": "Overflowing bin outside clinic",
        "description": "Bins near the clinic are overflowing every evening causing health concerns.",
        "category": "Garbage & Waste",
        "area": "Malad",
        "landmark": "Clinic Road",
        "latitude": 19.1901,
        "longitude": 72.8357,
        "priority": "Medium",
        "status": "Assigned",
        "citizen_name": "Nisha Singh",
        "email": "nisha@example.com",
        "phone": "9876387645",
        "support_count": 10,
        "created_at": datetime.utcnow() - timedelta(days=4),
        "updated_at": datetime.utcnow() - timedelta(hours=10),
        "department": "Solid Waste Management",
    },
    {
        "ticket_id": "URB-2026-00014",
        "title": "Streetlight flicker near school zone",
        "description": "The streetlights near the school zone flicker frequently at night and need inspection.",
        "category": "Street Lights",
        "area": "Borivali",
        "landmark": "School Zone",
        "latitude": 19.2250,
        "longitude": 72.8566,
        "priority": "High",
        "status": "Verified",
        "citizen_name": "Dev Patel",
        "email": "dev@example.com",
        "phone": "9823451234",
        "support_count": 15,
        "created_at": datetime.utcnow() - timedelta(days=8),
        "updated_at": datetime.utcnow() - timedelta(days=5),
        "department": "Electrical Department",
    },
    {
        "ticket_id": "URB-2026-00015",
        "title": "Broken traffic divider near school",
        "description": "A damaged divider near the school is creating unsafe traffic behavior.",
        "category": "Traffic",
        "area": "Mira Road",
        "landmark": "School Corner",
        "latitude": 19.2875,
        "longitude": 72.8657,
        "priority": "High",
        "status": "Reported",
        "citizen_name": "Esha Bhosale",
        "email": "esha@example.com",
        "phone": "9754321987",
        "support_count": 17,
        "created_at": datetime.utcnow() - timedelta(days=2),
        "updated_at": datetime.utcnow() - timedelta(days=1),
        "department": "Traffic Management",
    },
    {
        "ticket_id": "URB-2026-00016",
        "title": "Park bench damaged",
        "description": "Several benches in the lake park are broken and unsafe for senior citizens.",
        "category": "Parks",
        "area": "Bhayandar",
        "landmark": "Lake Park",
        "latitude": 19.3020,
        "longitude": 72.8527,
        "priority": "Low",
        "status": "Assigned",
        "citizen_name": "Kunal Shah",
        "email": "kunal@example.com",
        "phone": "9876123444",
        "support_count": 5,
        "created_at": datetime.utcnow() - timedelta(days=10),
        "updated_at": datetime.utcnow() - timedelta(days=8),
        "department": "Parks Department",
    },
    {
        "ticket_id": "URB-2026-00017",
        "title": "Dust bin missing at bus junction",
        "description": "There is no public dust bin at the busy bus junction and litter is accumulating.",
        "category": "Garbage & Waste",
        "area": "Kandivali",
        "landmark": "Bus Junction",
        "latitude": 19.2055,
        "longitude": 72.8612,
        "priority": "Medium",
        "status": "Reported",
        "citizen_name": "Tushar Nair",
        "email": "tushar@example.com",
        "phone": "9823018765",
        "support_count": 12,
        "created_at": datetime.utcnow() - timedelta(days=3),
        "updated_at": datetime.utcnow() - timedelta(days=2),
        "department": "Solid Waste Management",
    },
    {
        "ticket_id": "URB-2026-00018",
        "title": "Sewage overflow near grocery lane",
        "description": "Overflowing sewage near the grocery lane is creating a sanitation issue.",
        "category": "Drainage",
        "area": "Malad",
        "landmark": "Grocery Lane",
        "latitude": 19.1880,
        "longitude": 72.8405,
        "priority": "Critical",
        "status": "In Progress",
        "citizen_name": "Ritika Soni",
        "email": "ritika@example.com",
        "phone": "9812349090",
        "support_count": 31,
        "created_at": datetime.utcnow() - timedelta(days=2),
        "updated_at": datetime.utcnow() - timedelta(days=1),
        "department": "Water Department",
    },
    {
        "ticket_id": "URB-2026-00019",
        "title": "Water supply interruption in block C",
        "description": "Residents of block C are experiencing an irregular water supply for the second day.",
        "category": "Water Supply",
        "area": "Borivali",
        "landmark": "Block C",
        "latitude": 19.2287,
        "longitude": 72.8574,
        "priority": "High",
        "status": "Assigned",
        "citizen_name": "Amit Gokhale",
        "email": "amit@example.com",
        "phone": "9877012345",
        "support_count": 22,
        "created_at": datetime.utcnow() - timedelta(days=6),
        "updated_at": datetime.utcnow() - timedelta(days=2),
        "department": "Water Department",
    },
    {
        "ticket_id": "URB-2026-00020",
        "title": "Streetlight issue near pedestrian crossing",
        "description": "The crossing lights are not visible at night and the area is poorly lit.",
        "category": "Street Lights",
        "area": "Dahisar",
        "landmark": "Pedestrian Crossing",
        "latitude": 19.2580,
        "longitude": 72.8645,
        "priority": "Medium",
        "status": "Resolved",
        "citizen_name": "Saloni Joshi",
        "email": "saloni@example.com",
        "phone": "9722678901",
        "support_count": 7,
        "created_at": datetime.utcnow() - timedelta(days=12),
        "updated_at": datetime.utcnow() - timedelta(days=5),
        "resolved_at": datetime.utcnow() - timedelta(days=5),
        "department": "Electrical Department",
    },
    {
        "ticket_id": "URB-2026-00021",
        "title": "Crowded bus route on evening service",
        "description": "The evening bus route is overcrowded and not enough buses are running.",
        "category": "Public Transport",
        "area": "Mira Road",
        "landmark": "Central Bus Stand",
        "latitude": 19.2830,
        "longitude": 72.8715,
        "priority": "Medium",
        "status": "Verified",
        "citizen_name": "Yogesh Chavan",
        "email": "yogesh@example.com",
        "phone": "9825654321",
        "support_count": 14,
        "created_at": datetime.utcnow() - timedelta(days=4),
        "updated_at": datetime.utcnow() - timedelta(days=2),
        "department": "Public Transport",
    },
    {
        "ticket_id": "URB-2026-00022",
        "title": "Public park gate damaged",
        "description": "The public park gate is broken and not secure for evening visitors.",
        "category": "Parks",
        "area": "Kandivali",
        "landmark": "Park Gate 1",
        "latitude": 19.2133,
        "longitude": 72.8600,
        "priority": "Low",
        "status": "Reported",
        "citizen_name": "Priya Joshi",
        "email": "priya2@example.com",
        "phone": "9765201100",
        "support_count": 4,
        "created_at": datetime.utcnow() - timedelta(days=9),
        "updated_at": datetime.utcnow() - timedelta(days=8),
        "department": "Parks Department",
    },
    {
        "ticket_id": "URB-2026-00023",
        "title": "Open manhole outside apartment",
        "description": "An open manhole near the apartment building is dangerous for residents and drivers.",
        "category": "Drainage",
        "area": "Bhayandar",
        "landmark": "Apartment Gate",
        "latitude": 19.3027,
        "longitude": 72.8494,
        "priority": "Critical",
        "status": "Assigned",
        "citizen_name": "Mehul Parmar",
        "email": "mehul@example.com",
        "phone": "9898123456",
        "support_count": 27,
        "created_at": datetime.utcnow() - timedelta(days=1),
        "updated_at": datetime.utcnow() - timedelta(hours=4),
        "department": "Water Department",
    },
    {
        "ticket_id": "URB-2026-00024",
        "title": "Noisy generator near community center",
        "description": "A generator near the community center is creating harmful noise after sunset.",
        "category": "Noise Pollution",
        "area": "Dahisar",
        "landmark": "Community Center",
        "latitude": 19.2646,
        "longitude": 72.8650,
        "priority": "Low",
        "status": "Verified",
        "citizen_name": "Deepika Kulkarni",
        "email": "deepika@example.com",
        "phone": "9888001234",
        "support_count": 5,
        "created_at": datetime.utcnow() - timedelta(days=5),
        "updated_at": datetime.utcnow() - timedelta(days=2),
        "department": "Public Safety",
    },
    {
        "ticket_id": "URB-2026-00025",
        "title": "Signal countdown timer not working",
        "description": "The signal countdown timer is not working at a key junction causing confusion.",
        "category": "Traffic",
        "area": "Borivali",
        "landmark": "Main Junction",
        "latitude": 19.2300,
        "longitude": 72.8485,
        "priority": "Medium",
        "status": "Resolved",
        "citizen_name": "Arjun Shah",
        "email": "arjun@example.com",
        "phone": "9823123456",
        "support_count": 9,
        "created_at": datetime.utcnow() - timedelta(days=13),
        "updated_at": datetime.utcnow() - timedelta(days=7),
        "resolved_at": datetime.utcnow() - timedelta(days=7),
        "department": "Traffic Management",
    },
]


def seed_database(db: Session):
    if db.query(Department).count() > 0:
        return

    for name, code, description, avg_response_hours, rating in DEPARTMENT_SEED:
        department = Department(
            name=name,
            code=code,
            description=description,
            avg_response_hours=avg_response_hours,
            rating=rating,
        )
        db.add(department)
    db.flush()

    departments = {dept.name: dept for dept in db.query(Department).all()}

    for item in ISSUE_SEED:
        department_name = item["department"]
        issue = Issue(
            ticket_id=item["ticket_id"],
            title=item["title"],
            description=item["description"],
            category=item["category"],
            area=item["area"],
            landmark=item["landmark"],
            latitude=item["latitude"],
            longitude=item["longitude"],
            priority=item["priority"],
            priority_score=compute_priority_score(item["priority"], item["support_count"], 3, item["category"]),
            status=item["status"],
            department_id=departments[department_name].id,
            citizen_name=item["citizen_name"],
            email=item["email"],
            phone=item["phone"],
            support_count=item["support_count"],
            created_at=item["created_at"],
            updated_at=item["updated_at"],
            resolved_at=item.get("resolved_at"),
        )
        db.add(issue)
        db.flush()

        update_texts = {
            "Reported": "Citizen report was submitted to UrbanSync.",
            "Verified": "Issue verified by service desk and classified for routing.",
            "Assigned": f"Assigned to {department_name} for review and action.",
            "In Progress": "Field team has been notified and repair work is in progress.",
            "Resolved": "Service action has been completed and citizen feedback is requested.",
        }

        if item["status"] in update_texts:
            db.add(IssueUpdate(issue_id=issue.id, update_text=update_texts[item["status"]], stage=item["status"]))

        if item["support_count"]:
            db.add(IssueSupport(issue_id=issue.id, session_key=f"seed-{issue.id}", created_at=item["created_at"]))

        if item["status"] == "Resolved":
            db.add(Feedback(issue_id=issue.id, rating=4, comments="Service response was useful and timely.", created_at=item["resolved_at"] or item["created_at"]))

    poll = Poll(question="What should receive higher priority in your area?")
    db.add(poll)
    db.flush()

    options = [
        "Road Repairs",
        "Waste Collection",
        "Street Lighting",
        "Public Transport",
        "Parks",
    ]
    for opt_text in options:
        option = PollOption(poll_id=poll.id, text=opt_text, vote_count=8 + len(opt_text))
        db.add(option)
    db.flush()

    # Add sample votes for each option.
    for option in poll.options:
        db.add(PollVote(poll_id=poll.id, option_id=option.id, session_key=f"poll-{option.id}", created_at=datetime.utcnow()))

    db.commit()
